[package]
name = "flatline"
version = "0.1.1"
edition = "2024"
authors = ["holdxen"]
license = "MPL-2.0"
description = "An async SSH-2.0 client library for Rust"
readme = "README.md"
repository = "https://github.com/holdxen/flatline"
homepage = "https://github.com/holdxen/flatline"
keywords = ["ssh", "ssh2", "async", "client", "network"]
categories = ["network-programming", "asynchronous"]
exclude = [
    "**/.DS_Store"
]

[dependencies]
async-trait = "0.1"
bcrypt-pbkdf = "0.11"
bytes = "1"
cfg-if = "1.0.4"
derive_more = { version = "2.1", features = ["debug"] }
easy-ext = "1.0.3"
flate2 = { version = "1.1.9", features = ["zlib-rs"] }
indexmap = "2"
libcrux-ml-kem = "0.0.9"
openssl = "0.10"
rand = { version = "0.10", features = ["thread_rng"] }
regex = "1"
snafu = "0.9"
tokio = { version = "1", features = ["macros", "sync", "io-util", "rt"] }
tracing = { version = "0.1" }
umac = { package = "flatline-umac", git = "https://github.com/holdxen/umac.git", rev = "fb8eb2d90afc37e7e18a5aeea8a0cdf6ef2560fc", version = "0.1", optional = true }
shlex = "2.0"
bitflags = "2.13"
num_enum = "0.7"
async-recursion = "1.1.1"

[dev-dependencies]
anyhow = { version = "1.0.103", features = ["backtrace"] }
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.27.0"
tokio = { version = "1", features = ["full"] }
toml = "1.1.2"
tracing-subscriber = "0.3.23"
walkdir = "2.5.0"


[features]
umac = ["dep:umac"]
strict = []
openssl-v101 = ["openssl/v101"]
openssl-v102 = ["openssl/v102"]
openssl-v110 = ["openssl/v110"]
openssl-v111 = ["openssl/v111"]
openssl-vendored = ["openssl/vendored"]
